### ISSUE TITLE
Debugging an error during initial login

### ISSUE THREAD

**Issue by cbowns** [pelo-tech/whoop-google-sheets#2] opened 2020-10-28 15:37 UTC
Copied the base sheet on 2020-10-28, and stepping through the login process, I get an error on the initial Whoop auth:

![image](https://user-images.githubusercontent.com/474/97459215-c4f0bf00-18f8-11eb-957f-e4493046e0ef.png)

In the Chrome console, there's not much more info:

```
userCodeAppPanel:4 displayAlertLogging you in->Logging you into Whoop to obtain your tokens. This may take a few seconds
3562876441-warden_bin_i18n_warden.js:69 Net state changed from IDLE to BUSY
3562876441-warden_bin_i18n_warden.js:69 Net state changed from BUSY to IDLE
userCodeAppPanel:4 displayAlertError occurred. ->undefined
```

**Comment by DovOps** [comment] 2020-11-09 03:55
Really sorry about the delay in checking this out. Is this still an issue for you? I'll try to reproduce and revert back.

**Comment by DovOps** [comment] 2020-11-09 04:46
@cbowns - I cannot reproduce this issue - my login looks fine.  

Here are 3 things I suggest checking out

1.  Go  to Tools->Script Editor->View(on script editor screen)->Executions to see if you can get detailed logs about the failed method call. Does that show you anything meaningful? You should see something like this:
![image](https://user-images.githubusercontent.com/4614730/98501116-f9e50600-2256-11eb-88d5-4d1d37f1d803.png)
Does it show the status for your handleSidebarSubmit call as having 'failed'?   Click the row to expand and see any other logs. What do you see there?

1. Do you have special characters in your password? Things that might be unicode vs ascii? I don't think there's a charset encoding issue in the REST calls I make to Whoop but just in case that's one possibility.

1. Just to make sure you have the latest code, can you try cloning the [Whoop Spreadsheet Shareable](https://docs.google.com/spreadsheets/d/1q9tU4tkBLUi6oFsdLsO9HnOuMC-TEkrBXNoNXvLQt3Q/) again just to make sure you have the latest code, and try again?

Please let me know what you find out.

**Comment by DovOps** [comment] 2020-11-12 03:35
@cbowns  let me know if this is still an issue, otherwise I'll close it down as not reproducible

**Comment by DovOps** [comment] 2020-11-27 06:35
@cbowns  Can't reproduce this issue.  If this persists, please check the logs of the handleSidebarSubmit call in the stackdriver executions window and revert back.

**Closed as completed** 2020-11-29 04:54 UTC
Labels: bug, wontfix, cannot reproduce
